// German names for the Germany mode (Edeka / Rewe). The Italian original recipe names stay in data.js and are shown as the subtitle.
const ITEM_DE = {
  spaghetti: 'Spaghetti', penne: 'Penne', gnocchi: 'Gnocchi', riso: 'Risottoreis', basmati: 'Basmatireis', couscous: 'Couscous',
  pane: 'Brot', tortillas: 'Tortillas (Wraps)', ceci: 'Kichererbsen (Dose)', lenticchie: 'Linsen (Dose)', fagioli: 'Weiße Bohnen (Dose)',
  passata: 'Passierte Tomaten', pelati: 'Stückige Tomaten', tonno: 'Thunfisch in Olivenöl', pesto: 'Pesto', cocco: 'Kokosmilch',
  brodo: 'Gemüsebrühwürfel', olio: 'Olivenöl nativ extra', sale: 'Salz', latte: 'Milch', uova: 'Eier', mozzarella: 'Mozzarella',
  parmigiano: 'Parmesan / Grana gerieben', ricotta: 'Ricotta', burro: 'Butter', tofu: 'Tofu natur', pollo: 'Hähnchenbrustfilet',
  macinato: 'Hackfleisch', salsiccia: 'Salsiccia / Bratwurst', guanciale: 'Guanciale / Pancetta', merluzzo: 'Kabeljaufilet (TK)',
  salmone: 'Lachsfilet', pomodorini: 'Cherrytomaten', zucchine: 'Zucchini', melanzane: 'Aubergine', peperoni: 'Paprika',
  cipolle: 'Zwiebeln', aglio: 'Knoblauch', carote: 'Karotten', patate: 'Kartoffeln', spinaci: 'Spinat', broccoli: 'Brokkoli',
  funghi: 'Champignons', insalata: 'Salat', piselli: 'Erbsen', basilico: 'Basilikum', limoni: 'Zitronen',
};
const CAT_DE = { 'Fruit & veg': 'Obst & Gemüse', 'Meat & fish': 'Fleisch & Fisch', 'Dairy & eggs': 'Milch & Eier', 'Pasta & rice': 'Nudeln & Reis', Bakery: 'Backwaren', Pantry: 'Vorrat' };
const RECIPE_DE = {
  r01: { n: 'Spaghetti mit Tomatensauce und Basilikum', s: ['Knoblauch in Öl anbraten, passierte Tomaten und Salz zugeben und 10 Minuten köcheln lassen.', 'Spaghetti kochen, mit der Sauce und gezupftem Basilikum mischen und mit Parmesan bestreuen.'] },
  r02: { n: 'Spaghetti Carbonara', s: ['Den Guanciale ohne Öl knusprig braten.', 'Eier mit Parmesan und Pfeffer verrühren.', 'Die abgetropften Nudeln mit dem Guanciale vom Herd mischen, dann die Eiermasse mit einem Schuss Nudelwasser unterrühren.'] },
  r03: { n: 'Penne mit Zucchini und Ricotta', s: ['Zwiebel und gewürfelte Zucchini 10 Minuten in Öl weich dünsten.', 'Mit den gekochten Penne und dem Ricotta mischen und mit etwas Nudelwasser cremig rühren.'] },
  r04: { n: 'Spaghetti mit Thunfisch und Tomaten', s: ['Knoblauch anbraten, Tomaten zugeben und 10 Minuten köcheln.', 'Abgetropften Thunfisch unterheben und mit den Spaghetti mischen.'] },
  r05: { n: 'Champignon-Risotto', s: ['Zwiebel in Butter andünsten, den Reis 2 Minuten mitrösten.', 'Heiße Brühe nach und nach zugeben (ca. 16 Minuten), angebratene Champignons unterrühren.', 'Mit Butter und Parmesan abschließen.'] },
  r06: { n: 'Hähnchen mit Ofenkartoffeln', s: ['Kartoffeln, Zwiebel und Hähnchen würfeln, mit Öl und Salz mischen.', 'Bei 200 °C 40 Minuten im Ofen rösten, einmal wenden.'] },
  r07: { n: 'Hackbällchen in Tomatensauce', s: ['Hackfleisch, Ei, Parmesan und eingeweichtes Brot mischen und Bällchen formen.', 'Anbraten und in passierten Tomaten 20 Minuten köcheln lassen.'] },
  r08: { n: 'Salsiccia mit Kartoffeln', s: ['Wurststücke mit Zwiebel anbraten.', 'Gewürfelte Kartoffeln zugeben und zugedeckt 25 Minuten garen.'] },
  r09: { n: 'Zucchini-Frittata mit Salat', s: ['Zucchinischeiben anbraten und über verquirlte Eier mit Parmesan geben.', 'Zugedeckt bei niedriger Hitze stocken lassen, einmal wenden. Mit Salat servieren.'] },
  r10: { n: 'Auberginen-Parmigiana', s: ['Auberginenscheiben im Ofen rösten oder braten.', 'Mit Tomatensauce, Mozzarella und Parmesan schichten und 30 Minuten bei 180 °C backen.'] },
  r11: { n: 'Nudeln mit Kichererbsen', s: ['Zwiebel und Karotte andünsten, Tomaten, Kichererbsen und Wasser zugeben, 15 Minuten köcheln.', 'Die Nudeln direkt in der Suppe gar kochen.'] },
  r12: { n: 'Reissalat mit Thunfisch', s: ['Reis und ein Ei kochen, beides abkühlen lassen.', 'Mit Thunfisch, geviertelten Tomaten, gehacktem Ei und Öl mischen.'] },
  r13: { n: 'Kichererbsen-Spinat-Curry mit Reis', s: ['Zwiebel andünsten, Kichererbsen, Kokosmilch und Currygewürz zugeben, 10 Minuten köcheln.', 'Spinat unterrühren und über Basmatireis servieren.'] },
  r14: { n: 'Gnocchi mit Pesto', s: ['Gnocchi kochen, bis sie oben schwimmen.', 'Mit Pesto, halbierten Tomaten und Parmesan mischen.'] },
  r15: { n: 'Ofen-Kabeljau mit Kartoffeln', s: ['Kartoffelspalten 20 Minuten bei 200 °C rösten.', 'Kabeljau und Tomaten zugeben, 15 Minuten weiterbacken und mit Zitrone abschmecken.'] },
  r16: { n: 'Lachs mit Brokkoli und Reis', s: ['Lachs pro Seite 4 Minuten braten.', 'Brokkoli dämpfen, Reis kochen und mit Zitrone servieren.'] },
  r17: { n: 'Hähnchen-Paprika-Wraps', s: ['Hähnchenstreifen und Paprika anbraten, Bohnen und Tomaten zugeben.', 'In erwärmte Tortillas füllen und aufrollen.'] },
  r18: { n: 'Tofu-Gemüse-Pfanne mit Reis', s: ['Tofu ausdrücken, würfeln und goldbraun braten.', 'Gemüse anbraten, alles mischen und mit Reis servieren.'] },
  r19: { n: 'Linsensuppe', s: ['Zwiebel und Karotte andünsten, Linsen, Tomaten und Wasser zugeben und 20 Minuten köcheln.', 'Mit geröstetem Brot servieren.'] },
  r20: { n: 'Penne mit Brokkoli und Salsiccia', s: ['Salsiccia zerbröseln und mit Knoblauch anbraten.', 'Brokkoli mit den Nudeln mitkochen und alles mischen.'] },
  r21: { n: 'Quesadilla mit Spinat und Mozzarella', s: ['Spinat zusammenfallen lassen und mit Mozzarella zwischen zwei Tortillas legen.', 'In der Pfanne pro Seite 3 Minuten toasten.'] },
  r22: { n: 'Couscous mit Gemüse und Kichererbsen', s: ['Couscous mit heißem Wasser übergießen und 5 Minuten zugedeckt quellen lassen.', 'Gemüse anbraten, Kichererbsen zugeben und unter den Couscous mischen.'] },
  r23: { n: 'Selbstgemachter Burger mit Salat', s: ['Patties formen und pro Seite 4 Minuten braten.', 'Im Brot mit Salat und Tomate servieren.'] },
  r24: { n: 'Hähnchen-Erbsen-Eintopf', s: ['Hähnchenstücke mit Zwiebel anbraten.', 'Passierte Tomaten, Erbsen und einen Schuss Wasser zugeben und 20 Minuten köcheln.'] },
  r25: { n: 'Minestrone', s: ['Gemüse würfeln und 25 Minuten in Wasser köcheln.', 'Bohnen und Nudeln zugeben und weitere 10 Minuten garen.'] },
  r26: { n: 'Zitronen-Ricotta-Nudeln', s: ['Nudeln kochen.', 'Ricotta mit Zitronenschale, Zitronensaft und Parmesan verrühren und mit Nudelwasser lockern.', 'Mit den Nudeln mischen.'] },
  r27: { n: 'Spaghetti aglio e olio mit Cherrytomaten', s: ['Knoblauch sanft in Öl anbraten, halbierte Tomaten 3 Minuten mitgaren.', 'Mit den gekochten Spaghetti und einem Schuss Nudelwasser mischen.'] },
  r28: { n: 'Rührei mit Spinat und Brot', s: ['Spinat in Butter zusammenfallen lassen.', 'Verquirlte Eier zugeben und sanft stocken lassen.', 'Auf geröstetem Brot mit Parmesan servieren.'] },
  r29: { n: 'Champignon-Omelett mit Salat', s: ['Champignons in der Pfanne erwärmen.', 'Verquirlte Eier mit Parmesan zugeben und nach dem Stocken zusammenklappen.', 'Mit Salat servieren.'] },
  r30: { n: 'Hähnchen mit Paprika', s: ['Hähnchenstreifen in Öl anbraten.', 'Zwiebel und Paprikastreifen zugeben und 10 Minuten weich garen.'] },
  r31: { n: 'Zitronenhähnchen mit Reis', s: ['Hähnchenscheiben in Butter anbraten.', 'Zitronensaft und einen Schuss Wasser zugeben und 5 Minuten köcheln.', 'Über gekochtem Reis servieren.'] },
  r32: { n: 'Hähnchenstreifen mit Zucchini', s: ['Hähnchenstreifen mit Knoblauch goldbraun braten.', 'Zucchinischeiben zugeben und 8 Minuten garen.'] },
  r33: { n: 'Hähnchen-Bohnen-Salat', s: ['Hähnchenstreifen braten und etwas abkühlen lassen.', 'Mit Bohnen, Salat, Tomaten und Öl mischen.'] },
  r34: { n: 'Thunfisch-Bohnen-Salat', s: ['Abgetropfte Bohnen, Thunfisch, Zwiebelringe und Tomaten mit Öl mischen.', 'Mit Brot servieren.'] },
  r35: { n: 'Ofenlachs mit Kartoffeln', s: ['Kartoffelspalten 20 Minuten bei 200 °C rösten.', 'Lachs und Zitrone zugeben und 12 Minuten backen.'] },
  r36: { n: 'Kabeljau in Tomatensauce', s: ['Knoblauch in Öl andünsten, Tomaten 5 Minuten mitgaren.', 'Kabeljau zugeben, zugedeckt 10 Minuten garen. Mit Brot servieren.'] },
  r37: { n: 'Burger mit Kartoffeln', s: ['Kartoffelspalten 25 Minuten bei 200 °C rösten.', 'Patties pro Seite 4 Minuten braten und mit Salat servieren.'] },
  r38: { n: 'Schnelles Ragù mit Penne', s: ['Hackfleisch mit Zwiebel und Karotte anbraten.', 'Passierte Tomaten zugeben und 15 Minuten köcheln.', 'Mit Penne und Parmesan mischen.'] },
  r39: { n: 'Tofu-Curry mit Reis', s: ['Tofu würfeln und anbraten.', 'Zwiebel, Erbsen, Kokosmilch und Currygewürz zugeben und 8 Minuten köcheln.', 'Über Basmatireis servieren.'] },
  r40: { n: 'Tofu-Rührei-Wraps mit Spinat', s: ['Tofu mit Zwiebel und Gewürzen in der Pfanne zerbröseln.', 'Spinat zugeben, bis er zusammenfällt.', 'Tortillas erwärmen und füllen.'] },
  r41: { n: 'Linsen mit Salsiccia', s: ['Zerbröselte Salsiccia mit Zwiebel und Karotte anbraten.', 'Linsen und passierte Tomaten zugeben und 15 Minuten köcheln.'] },
  r42: { n: 'Nudeln mit Bohnen', s: ['Zwiebel und Karotte andünsten, Tomaten, Bohnen und Wasser zugeben und 15 Minuten köcheln.', 'Die Nudeln in der Suppe gar kochen.'] },
  r43: { n: 'Kichererbsen-Spinat-Suppe', s: ['Zwiebel und Knoblauch andünsten, Kichererbsen und Wasser zugeben, 12 Minuten köcheln.', 'Spinat unterrühren. Mit geröstetem Brot servieren.'] },
  r44: { n: 'Gnocchi alla Sorrentina', s: ['Tomatensauce mit Basilikum 10 Minuten köcheln.', 'Gnocchi kochen, mit Sauce und Mozzarella mischen.', 'Mit Parmesan 5 Minuten überbacken.'] },
  r45: { n: 'Gnocchi mit Salsiccia und Champignons', s: ['Salsiccia mit Zwiebel anbraten, Champignons 5 Minuten mitgaren.', 'Gnocchi kochen und untermischen.'] },
  r46: { n: 'Spinat-Ricotta-Risotto', s: ['Zwiebel andünsten, Reis rösten, heiße Brühe nach und nach zugeben (ca. 16 Minuten).', 'Spinat, Ricotta und Parmesan unterheben.'] },
  r47: { n: 'Gebratener Reis mit Ei und Erbsen', s: ['Reis kochen und abkühlen lassen.', 'Karotte und Erbsen anbraten, beiseiteschieben und die Eier rühren.', 'Reis zugeben und heiß durchschwenken.'] },
  r48: { n: 'Couscous mit Hähnchen und Gemüse', s: ['Couscous mit heißem Wasser übergießen und 5 Minuten quellen lassen.', 'Hähnchenstücke mit gewürfeltem Gemüse 10 Minuten braten und untermischen.'] },
  r49: { n: 'Reis-Bohnen-Bowl', s: ['Reis kochen.', 'Bohnen mit gewürfelter Paprika und Zwiebel erwärmen.', 'Mit frischen Tomaten toppen.'] },
  r50: { n: 'Zucchini-Carbonara', s: ['Geraspelte Zucchini anbraten, bis sie weich sind.', 'Eier mit Parmesan verrühren und mit den heißen Nudeln vom Herd mischen.'] },
};
