// Prices are ESTIMATES (EUR per pack) seeded for convenience. Not live data from any store.
// [id, name, en, category, pack, unit, pam, gigante, staple]
const RAW_ITEMS = [
 ["spaghetti","Spaghetti","Spaghetti","Pasta & rice",500,"g",1.19,1.29],
 ["penne","Penne rigate","Penne","Pasta & rice",500,"g",1.19,1.25],
 ["gnocchi","Gnocchi di patate","Potato gnocchi","Pasta & rice",500,"g",1.39,1.49],
 ["riso","Riso Arborio","Arborio rice","Pasta & rice",1000,"g",2.49,2.39],
 ["basmati","Riso basmati","Basmati rice","Pasta & rice",500,"g",2.29,2.49],
 ["couscous","Cous cous","Couscous","Pasta & rice",500,"g",1.79,1.69],
 ["pane","Pane","Bread","Bakery",500,"g",1.90,1.79],
 ["tortillas","Tortillas di grano","Wheat tortillas","Bakery",200,"g",1.99,2.09],
 ["ceci","Ceci in scatola","Canned chickpeas","Pantry",400,"g",0.99,1.05],
 ["lenticchie","Lenticchie in scatola","Canned lentils","Pantry",400,"g",1.19,1.29],
 ["fagioli","Fagioli cannellini in scatola","Canned cannellini beans","Pantry",400,"g",0.95,0.99],
 ["passata","Passata di pomodoro","Tomato passata","Pantry",700,"g",1.09,1.19],
 ["pelati","Pomodori pelati","Peeled tomatoes","Pantry",400,"g",0.79,0.85],
 ["tonno","Tonno in olio d'oliva (2x80g)","Tuna in olive oil","Pantry",160,"g",2.79,2.99],
 ["pesto","Pesto alla genovese","Basil pesto","Pantry",190,"g",1.79,1.89],
 ["cocco","Latte di cocco","Coconut milk","Pantry",400,"ml",1.29,1.39],
 ["brodo","Dado vegetale (10 pz)","Vegetable stock cubes","Pantry",10,"pc",1.49,1.55,true],
 ["olio","Olio extra vergine d'oliva 1L","Extra virgin olive oil","Pantry",1000,"ml",7.99,8.49,true],
 ["sale","Sale fino 1kg","Salt","Pantry",1000,"g",0.59,0.55,true],
 ["latte","Latte","Milk","Dairy & eggs",1000,"ml",1.59,1.49],
 ["uova","Uova (6)","Eggs (6)","Dairy & eggs",6,"pc",2.19,2.09],
 ["mozzarella","Mozzarella 125g","Mozzarella","Dairy & eggs",125,"g",0.99,1.09],
 ["parmigiano","Parmigiano grattugiato","Grated parmesan","Dairy & eggs",100,"g",2.49,2.39],
 ["ricotta","Ricotta","Ricotta","Dairy & eggs",250,"g",1.99,2.09],
 ["burro","Burro","Butter","Dairy & eggs",250,"g",2.69,2.79],
 ["tofu","Tofu naturale","Plain tofu","Dairy & eggs",200,"g",1.99,2.19],
 ["pollo","Petto di pollo","Chicken breast","Meat & fish",500,"g",4.79,4.99],
 ["macinato","Macinato di manzo","Minced beef","Meat & fish",400,"g",4.29,4.49],
 ["salsiccia","Salsiccia","Sausage","Meat & fish",400,"g",3.99,3.79],
 ["guanciale","Guanciale/pancetta","Guanciale","Meat & fish",150,"g",2.29,2.49],
 ["merluzzo","Filetti di merluzzo surgelati","Frozen cod fillets","Meat & fish",400,"g",4.49,4.69],
 ["salmone","Salmone","Salmon","Meat & fish",250,"g",4.99,5.29],
 ["pomodorini","Pomodorini","Cherry tomatoes","Fruit & veg",500,"g",1.99,1.89],
 ["zucchine","Zucchine","Courgettes","Fruit & veg",500,"g",1.49,1.39],
 ["melanzane","Melanzane","Aubergines","Fruit & veg",500,"g",1.69,1.59],
 ["peperoni","Peperoni","Peppers","Fruit & veg",500,"g",2.29,2.19],
 ["cipolle","Cipolle","Onions","Fruit & veg",1000,"g",1.29,1.19],
 ["aglio","Aglio","Garlic","Fruit & veg",100,"g",0.89,0.95],
 ["carote","Carote","Carrots","Fruit & veg",1000,"g",1.19,1.09],
 ["patate","Patate","Potatoes","Fruit & veg",2000,"g",2.29,2.19],
 ["spinaci","Spinaci","Spinach","Fruit & veg",300,"g",1.69,1.79],
 ["broccoli","Broccoli","Broccoli","Fruit & veg",500,"g",1.79,1.89],
 ["funghi","Funghi champignon","Mushrooms","Fruit & veg",400,"g",2.19,2.09],
 ["insalata","Insalata mista","Mixed salad","Fruit & veg",150,"g",1.39,1.29],
 ["piselli","Piselli surgelati","Frozen peas","Fruit & veg",450,"g",1.59,1.69],
 ["basilico","Basilico (mazzetto)","Basil bunch","Fruit & veg",1,"pc",0.99,1.09],
 ["limoni","Limoni","Lemons","Fruit & veg",500,"g",1.19,1.29],
];
// ing: [itemId, quantity PER SERVING in item's unit]. grp: protein group for variety.
const RECIPES = [
 {id:"r01",name:"Spaghetti al pomodoro e basilico",en:"Spaghetti with tomato & basil",veg:true,grp:"pasta",min:20,
  ing:[["spaghetti",90],["passata",120],["basilico",0.1],["aglio",3],["parmigiano",10],["olio",10]],
  steps:["Fry garlic in oil, add passata and salt, simmer 10 min.","Boil spaghetti, toss with sauce and torn basil, top with parmesan."]},
 {id:"r02",name:"Pasta alla carbonara",en:"Carbonara",veg:false,grp:"pork",min:25,
  ing:[["spaghetti",90],["uova",1],["guanciale",40],["parmigiano",15]],
  steps:["Crisp the guanciale in a pan, no oil.","Mix eggs and parmesan with pepper.","Toss drained pasta with guanciale off the heat, then add the egg mix with a splash of pasta water."]},
 {id:"r03",name:"Penne zucchine e ricotta",en:"Penne with courgette & ricotta",veg:true,grp:"pasta",min:20,
  ing:[["penne",90],["zucchine",150],["ricotta",60],["cipolle",30],["parmigiano",10],["olio",10]],
  steps:["Soften onion and diced courgettes in oil for 10 min.","Toss with cooked penne and ricotta, loosen with pasta water."]},
 {id:"r04",name:"Spaghetti al tonno",en:"Tuna & tomato spaghetti",veg:false,grp:"fish",min:20,
  ing:[["spaghetti",90],["tonno",60],["pelati",100],["aglio",3],["olio",10]],
  steps:["Fry garlic, add peeled tomatoes and cook 10 min.","Fold in drained tuna, toss with spaghetti."]},
 {id:"r05",name:"Risotto ai funghi",en:"Mushroom risotto",veg:true,grp:"rice",min:35,
  ing:[["riso",80],["funghi",120],["cipolle",30],["brodo",0.3],["parmigiano",15],["burro",10]],
  steps:["Sweat onion in butter, toast rice 2 min.","Add hot stock a ladle at a time for ~16 min, stir in sautéed mushrooms.","Finish with butter and parmesan."]},
 {id:"r06",name:"Pollo e patate al forno",en:"Roast chicken & potatoes",veg:false,grp:"chicken",min:50,
  ing:[["pollo",150],["patate",250],["cipolle",30],["olio",15]],
  steps:["Cube potatoes, onion and chicken, toss with oil and salt.","Roast at 200°C for 40 min, turning once."]},
 {id:"r07",name:"Polpette al sugo",en:"Meatballs in tomato sauce",veg:false,grp:"beef",min:45,
  ing:[["macinato",120],["uova",0.3],["parmigiano",15],["passata",150],["pane",30],["olio",8]],
  steps:["Mix mince, egg, parmesan and soaked bread; shape balls.","Brown, then simmer in passata 20 min."]},
 {id:"r08",name:"Salsiccia e patate",en:"Sausage & potatoes",veg:false,grp:"pork",min:40,
  ing:[["salsiccia",130],["patate",250],["cipolle",30],["olio",8]],
  steps:["Brown sausage pieces with onion.","Add diced potatoes, cover and cook 25 min."]},
 {id:"r09",name:"Frittata di zucchine con insalata",en:"Courgette frittata & salad",veg:true,grp:"egg",min:25,
  ing:[["uova",2.5],["zucchine",150],["parmigiano",15],["insalata",50],["olio",10]],
  steps:["Sauté sliced courgettes, pour over beaten eggs and parmesan.","Cook covered on low heat, flip once. Serve with salad."]},
 {id:"r10",name:"Parmigiana di melanzane",en:"Aubergine parmigiana",veg:true,grp:"veg",min:60,
  ing:[["melanzane",250],["passata",150],["mozzarella",62.5],["parmigiano",15],["olio",15]],
  steps:["Roast or fry aubergine slices.","Layer with passata, mozzarella and parmesan; bake 30 min at 180°C."]},
 {id:"r11",name:"Pasta e ceci",en:"Pasta & chickpeas",veg:true,grp:"legume",min:30,
  ing:[["penne",70],["ceci",200],["passata",80],["cipolle",30],["carote",40],["olio",10]],
  steps:["Soften onion and carrot, add passata, chickpeas and water, simmer 15 min.","Cook pasta in the soup until tender."]},
 {id:"r12",name:"Insalata di riso al tonno",en:"Rice salad with tuna",veg:false,grp:"fish",min:25,
  ing:[["riso",80],["tonno",50],["pomodorini",100],["uova",1],["olio",10]],
  steps:["Boil rice and an egg, cool both.","Mix with tuna, quartered tomatoes, chopped egg and oil."]},
 {id:"r13",name:"Curry di ceci e spinaci con riso",en:"Chickpea & spinach curry",veg:true,grp:"legume",min:30,
  ing:[["ceci",150],["spinaci",150],["cocco",100],["basmati",80],["cipolle",30],["olio",8]],
  steps:["Soften onion, add chickpeas, coconut milk and your spices, simmer 10 min.","Wilt in spinach, serve over basmati."]},
 {id:"r14",name:"Gnocchi al pesto",en:"Gnocchi with pesto",veg:true,grp:"pasta",min:15,
  ing:[["gnocchi",200],["pesto",50],["parmigiano",10],["pomodorini",60]],
  steps:["Boil gnocchi until they float.","Toss with pesto, halved tomatoes and parmesan."]},
 {id:"r15",name:"Merluzzo al forno con patate",en:"Baked cod with potatoes",veg:false,grp:"fish",min:40,
  ing:[["merluzzo",150],["patate",200],["pomodorini",100],["limoni",30],["olio",10]],
  steps:["Roast potato wedges 20 min at 200°C.","Add cod and tomatoes, bake 15 min more, finish with lemon."]},
 {id:"r16",name:"Salmone con broccoli e riso",en:"Salmon, broccoli & rice",veg:false,grp:"fish",min:30,
  ing:[["salmone",125],["broccoli",150],["riso",70],["limoni",30],["olio",8]],
  steps:["Pan-sear salmon 4 min per side.","Steam broccoli, boil rice, serve with lemon."]},
 {id:"r17",name:"Burrito di pollo e peperoni",en:"Chicken & pepper wraps",veg:false,grp:"chicken",min:25,
  ing:[["tortillas",100],["pollo",120],["peperoni",100],["fagioli",100],["passata",40],["olio",8]],
  steps:["Stir-fry chicken strips and peppers, add beans and passata.","Fill warmed tortillas and roll."]},
 {id:"r18",name:"Tofu saltato con verdure e riso",en:"Stir-fried tofu & veg with rice",veg:true,grp:"tofu",min:25,
  ing:[["tofu",120],["peperoni",100],["carote",60],["zucchine",80],["riso",70],["olio",10]],
  steps:["Press and cube tofu, fry until golden.","Stir-fry vegetables, combine, serve with rice."]},
 {id:"r19",name:"Zuppa di lenticchie",en:"Lentil soup",veg:true,grp:"legume",min:30,
  ing:[["lenticchie",200],["carote",50],["cipolle",30],["passata",60],["pane",40],["olio",10]],
  steps:["Soften onion and carrot, add lentils, passata and water, simmer 20 min.","Serve with toasted bread."]},
 {id:"r20",name:"Penne broccoli e salsiccia",en:"Penne, broccoli & sausage",veg:false,grp:"pork",min:25,
  ing:[["penne",90],["broccoli",150],["salsiccia",80],["aglio",3],["olio",8]],
  steps:["Crumble and brown sausage with garlic.","Boil broccoli with the pasta, toss everything together."]},
 {id:"r21",name:"Quesadilla spinaci e mozzarella",en:"Spinach & mozzarella quesadilla",veg:true,grp:"cheese",min:15,
  ing:[["tortillas",100],["spinaci",100],["mozzarella",62.5],["olio",5]],
  steps:["Wilt spinach, layer with mozzarella between tortillas.","Toast in a pan 3 min per side."]},
 {id:"r22",name:"Cous cous con verdure e ceci",en:"Veggie & chickpea couscous",veg:true,grp:"legume",min:20,
  ing:[["couscous",80],["zucchine",100],["peperoni",100],["ceci",100],["pomodorini",60],["olio",10]],
  steps:["Pour hot water over couscous, cover 5 min.","Sauté vegetables, add chickpeas, mix through."]},
 {id:"r23",name:"Hamburger casalingo con insalata",en:"Home-made burger & salad",veg:false,grp:"beef",min:25,
  ing:[["macinato",130],["pane",60],["insalata",60],["pomodorini",60],["olio",5]],
  steps:["Shape and pan-fry patties 4 min per side.","Serve in bread with salad and tomato."]},
 {id:"r24",name:"Pollo e piselli in umido",en:"Chicken & peas stew",veg:false,grp:"chicken",min:35,
  ing:[["pollo",150],["piselli",150],["cipolle",30],["passata",60],["olio",10]],
  steps:["Brown chicken pieces with onion.","Add passata, peas and a splash of water, simmer 20 min."]},
 {id:"r25",name:"Minestrone",en:"Minestrone",veg:true,grp:"veg",min:40,
  ing:[["patate",100],["carote",60],["zucchine",80],["cipolle",30],["fagioli",100],["penne",40],["olio",8]],
  steps:["Dice vegetables and simmer in water 25 min.","Add beans and pasta, cook 10 more minutes."]},
 {id:"r26",name:"Pasta limone e ricotta",en:"Lemon & ricotta pasta",veg:true,grp:"pasta",min:15,
  ing:[["penne",90],["ricotta",60],["limoni",30],["parmigiano",10],["olio",8]],
  steps:["Boil the pasta.","Mix ricotta with lemon zest, juice and parmesan, loosen with pasta water.","Toss with the pasta."]},
 {id:"r27",name:"Spaghetti aglio, olio e pomodorini",en:"Garlic, oil & cherry tomato spaghetti",veg:true,grp:"pasta",min:15,
  ing:[["spaghetti",90],["aglio",4],["pomodorini",60],["olio",12]],
  steps:["Gently fry garlic in oil, add halved tomatoes for 3 min.","Toss with the cooked spaghetti and a splash of pasta water."]},
 {id:"r28",name:"Uova strapazzate con spinaci e pane",en:"Scrambled eggs, spinach & toast",veg:true,grp:"egg",min:10,
  ing:[["uova",3],["spinaci",100],["pane",60],["parmigiano",10],["burro",8]],
  steps:["Wilt spinach in butter.","Add beaten eggs and stir softly until just set.","Serve on toasted bread with parmesan."]},
 {id:"r29",name:"Omelette ai funghi con insalata",en:"Mushroom omelette & salad",veg:true,grp:"egg",min:15,
  ing:[["uova",3],["funghi",100],["parmigiano",10],["insalata",50],["olio",8]],
  steps:["Warm the mushrooms in a pan.","Pour in beaten eggs and parmesan, fold when set.","Serve with salad."]},
 {id:"r30",name:"Pollo ai peperoni",en:"Chicken with peppers",veg:false,grp:"chicken",min:20,
  ing:[["pollo",170],["peperoni",120],["cipolle",30],["olio",10]],
  steps:["Brown chicken strips in oil.","Add sliced onion and peppers, cook 10 min until soft."]},
 {id:"r31",name:"Pollo al limone con riso",en:"Lemon chicken with rice",veg:false,grp:"chicken",min:30,
  ing:[["pollo",160],["limoni",30],["riso",70],["burro",8]],
  steps:["Sear chicken slices in butter.","Add lemon juice and a splash of water, simmer 5 min.","Serve over boiled rice."]},
 {id:"r32",name:"Straccetti di pollo e zucchine",en:"Chicken strips & courgettes",veg:false,grp:"chicken",min:20,
  ing:[["pollo",170],["zucchine",150],["aglio",3],["olio",10]],
  steps:["Fry chicken strips with garlic until golden.","Add sliced courgettes and cook 8 min."]},
 {id:"r33",name:"Insalata di pollo e fagioli",en:"Chicken & bean salad",veg:false,grp:"chicken",min:15,
  ing:[["pollo",150],["fagioli",100],["insalata",60],["pomodorini",80],["olio",10]],
  steps:["Pan-cook chicken strips, let cool a little.","Toss with beans, salad leaves, tomatoes and oil."]},
 {id:"r34",name:"Tonno e fagioli con cipolla",en:"Tuna & bean salad",veg:false,grp:"fish",min:10,
  ing:[["tonno",80],["fagioli",150],["cipolle",30],["pomodorini",60],["pane",40],["olio",8]],
  steps:["Mix drained beans, tuna, sliced onion and tomatoes with oil.","Serve with bread."]},
 {id:"r35",name:"Salmone al forno con patate",en:"Baked salmon & potatoes",veg:false,grp:"fish",min:35,
  ing:[["salmone",140],["patate",200],["limoni",30],["olio",8]],
  steps:["Roast potato wedges 20 min at 200°C.","Add salmon and lemon, bake 12 min."]},
 {id:"r36",name:"Merluzzo in umido con pomodorini",en:"Cod stewed with tomatoes",veg:false,grp:"fish",min:22,
  ing:[["merluzzo",150],["pomodorini",120],["aglio",3],["olio",10],["pane",30]],
  steps:["Soften garlic in oil, add tomatoes for 5 min.","Add cod, cover and cook 10 min. Serve with bread."]},
 {id:"r37",name:"Hamburger con patate",en:"Burger with potatoes",veg:false,grp:"beef",min:30,
  ing:[["macinato",130],["patate",200],["insalata",40],["olio",8]],
  steps:["Roast potato wedges 25 min at 200°C.","Pan-fry the patties 4 min per side. Serve with salad."]},
 {id:"r38",name:"Ragù veloce con penne",en:"Quick ragù penne",veg:false,grp:"beef",min:30,
  ing:[["macinato",100],["passata",120],["cipolle",30],["carote",30],["penne",90],["parmigiano",10]],
  steps:["Brown mince with diced onion and carrot.","Add passata, simmer 15 min.","Toss with penne and parmesan."]},
 {id:"r39",name:"Riso al curry con tofu",en:"Tofu curry rice",veg:true,grp:"tofu",min:22,
  ing:[["tofu",150],["basmati",70],["cocco",80],["piselli",60],["cipolle",30]],
  steps:["Cube and brown the tofu.","Add onion, peas, coconut milk and your curry spices, simmer 8 min.","Serve over basmati."]},
 {id:"r40",name:"Tofu strapazzato con spinaci e tortillas",en:"Tofu scramble wraps",veg:true,grp:"tofu",min:20,
  ing:[["tofu",150],["spinaci",100],["tortillas",100],["cipolle",20],["olio",8]],
  steps:["Crumble tofu into a pan with onion and spices.","Add spinach until wilted.","Warm tortillas and fill."]},
 {id:"r41",name:"Lenticchie in umido con salsiccia",en:"Lentils with sausage",veg:false,grp:"pork",min:30,
  ing:[["lenticchie",150],["salsiccia",100],["passata",60],["carote",30],["cipolle",30]],
  steps:["Brown crumbled sausage with onion and carrot.","Add lentils and passata, simmer 15 min."]},
 {id:"r42",name:"Pasta e fagioli",en:"Pasta & beans",veg:true,grp:"legume",min:30,
  ing:[["penne",70],["fagioli",150],["passata",70],["carote",30],["cipolle",30],["olio",8]],
  steps:["Soften onion and carrot, add passata, beans and water, simmer 15 min.","Cook the pasta in the soup until tender."]},
 {id:"r43",name:"Zuppa di ceci e spinaci",en:"Chickpea & spinach soup",veg:true,grp:"legume",min:25,
  ing:[["ceci",150],["spinaci",100],["cipolle",30],["aglio",3],["pane",40],["olio",8]],
  steps:["Soften onion and garlic, add chickpeas and water, simmer 12 min.","Stir in spinach. Serve with toasted bread."]},
 {id:"r44",name:"Gnocchi alla sorrentina",en:"Gnocchi sorrentina",veg:true,grp:"cheese",min:25,
  ing:[["gnocchi",200],["passata",100],["mozzarella",62.5],["parmigiano",10],["basilico",0.1]],
  steps:["Simmer passata with basil 10 min.","Boil gnocchi, mix with sauce and mozzarella.","Grill 5 min with parmesan on top."]},
 {id:"r45",name:"Gnocchi con salsiccia e funghi",en:"Gnocchi with sausage & mushrooms",veg:false,grp:"pork",min:25,
  ing:[["gnocchi",200],["salsiccia",80],["funghi",100],["cipolle",20]],
  steps:["Brown sausage with onion, add mushrooms for 5 min.","Boil gnocchi and toss through."]},
 {id:"r46",name:"Risotto spinaci e ricotta",en:"Spinach & ricotta risotto",veg:true,grp:"rice",min:30,
  ing:[["riso",80],["spinaci",100],["ricotta",50],["cipolle",30],["brodo",0.3],["parmigiano",10]],
  steps:["Sweat onion, toast rice, add hot stock gradually for ~16 min.","Fold in spinach, ricotta and parmesan."]},
 {id:"r47",name:"Riso saltato con uova e piselli",en:"Egg fried rice with peas",veg:true,grp:"egg",min:20,
  ing:[["riso",80],["uova",2],["piselli",60],["carote",40],["olio",8]],
  steps:["Boil rice and cool it.","Stir-fry carrot and peas, push aside and scramble the eggs.","Add rice and toss hot."]},
 {id:"r48",name:"Cous cous al pollo e verdure",en:"Chicken & veg couscous",veg:false,grp:"chicken",min:20,
  ing:[["couscous",70],["pollo",130],["zucchine",80],["peperoni",80],["olio",8]],
  steps:["Pour hot water over couscous, cover 5 min.","Fry chicken pieces with diced veg 10 min and mix through."]},
 {id:"r49",name:"Bowl di riso e fagioli",en:"Rice & bean bowl",veg:true,grp:"legume",min:20,
  ing:[["riso",70],["fagioli",100],["peperoni",80],["pomodorini",60],["cipolle",20],["olio",8]],
  steps:["Boil the rice.","Warm beans with diced pepper and onion.","Top with fresh tomatoes."]},
 {id:"r50",name:"Carbonara di zucchine",en:"Courgette carbonara",veg:true,grp:"pasta",min:20,
  ing:[["spaghetti",90],["uova",1.5],["zucchine",120],["parmigiano",15]],
  steps:["Brown grated courgettes until soft.","Mix eggs and parmesan, toss with hot pasta off the heat."]},
];
// Approximate protein (g) per 100 g/ml, or per piece for pc items. General nutrition values, shown as "≈".
const PROT = {spaghetti:12.5,penne:12.5,gnocchi:4,riso:7,basmati:8,couscous:13,pane:8,tortillas:8,ceci:7,lenticchie:8,fagioli:6.5,passata:1.5,pelati:1.2,tonno:25,pesto:5,cocco:2,brodo:0,olio:0,sale:0,latte:3.3,uova:6.5,mozzarella:18,parmigiano:33,ricotta:11,burro:0.8,tofu:12,pollo:23,macinato:20,salsiccia:14,guanciale:10,merluzzo:17,salmone:20,pomodorini:1,zucchine:1.2,melanzane:1,peperoni:1,cipolle:1.2,aglio:6,carote:0.9,patate:2,spinaci:3,broccoli:3,funghi:2.5,insalata:1.5,piselli:5,basilico:0,limoni:0.7};
